name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  retrofit: ^3.0.1+1
  json_annotation: ^4.6.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  flash: ^2.0.3+3
  flutter_bloc: ^8.1.1
  auto_route: ^5.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  retrofit_generator: ^4.0.3+1
  json_serializable: ^6.3.1
  auto_route_generator: ^5.0.2
  injectable_generator: ^1.5.4

flutter:
  uses-material-design: true
